version: "3"
services:
  app:
    build: .
    container_name: blog-app
    command: uvicorn blog.main:app --host 0.0.0.0 --port 90 --reload
    ports:
      - 8080:90
    volumes:
       - .:/fast-api
  production_db:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5433:5432
    env_file:
      - database.env
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - database_network

  database_mangement:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8888:80
    env_file:
      - database_mangement.env
    volumes:
      - pgadmins:/var/lib/pgadmin/cache
    networks:
      - database_network


volumes:
  database:
  pgadmins:


networks:
  database_network:

      
    