version: "3"
services:
  api:
    build: .
    image: fast-api
    command: sh -c "uvicorn blog.main:app --reload --host localhost --port 80"
    ports:
      - "8000:80"
    volumes:
      - .:/fast-api:ro