version: "3"  #use latets version 
services:
  app:
    build: .
    container_name: blog-app
    command: uvicorn blog.main:app --host 0.0.0.0 --port 90 --reload
    ports:
      - 8080:90
    volumes:
       - .:/fast-api   # do not use it in produiction 
  production_db:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./blog/database.env
   
   
  # zbt network, find a way to run a docker with migrations, adjust voulme
  
  database_mangement:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8888:80
    env_file:
      - ./blog/database_mangement.env

      
    #single connection 
    #strutcre of the project
    #authtionction 
    #select models orm 
    